paths:

  /api/products:

    get:

      summary: Obtiene todos los productos

      tags:

        - Products

      responses:

        "200":

          description: Datos obtenidos satisfactoriamente

          content:

            application/json:

              schema:

                type: array

                items:

                  $ref: "#/components/schemas/Product"

        "500":

          description: Error interno del servidor
    post:

      summary: Crea un nuevo producto

      tags:

        - Products

      requestBody:

        required: true

        content:

          application/json:

            schema:

              $ref: "#/components/requestBodies/CreateProduct"

      responses:

        "201":

          description: Usuario creado correctamente

          content:

            application/json:

              schema:

                $ref: "#/components/schemas/Product"

        "500":

          description: Error interno del servidor


  /api/products/{id}:

    get:

      summary: Obtiene un producto por id

      tags:

        - Products

      parameters:

        - name: id

          in: path

          required: true

          description: ID del producto que se solicita

          schema:

            type: string

      responses:

        "200":

          description: Producto encontrado

          content:

            application/json:

              schema:

                $ref: "#/components/schemas/Product"

        "500":

          description: Error interno del servidor

    put:

      summary: Actualiza un producto por id

      tags:

        - Products

      parameters:

        - name: id

          in: path

          required: true

          description: ID del producto que se solicita

          schema:

            type: string

      requestBody:

        required: true

        content:

          application/json:

            schema:

              $ref: "#/components/requestBodies/UpdateProduct"

      responses:

        "200":

          description: Producto actualizado correctamente

          content:

            application/json:

              schema:

                $ref: "#/components/schemas/Product"

        "500":

          description: Error interno del servidor
    delete:
      
        summary: Elimina un producto por id
  
        tags:
  
          - Products
  
        parameters:
  
          - name: id
  
            in: path
  
            required: true
  
            description: ID del producto que se solicita
  
            schema:
  
              type: string
  
        responses:
  
          "200":
  
            description: Producto eliminado correctamente
  
          "500":
  
            description: Error interno del servidor


components:

  schemas:

    Product:

      type: object

      properties:

        _id:

          type: string

          description: ID generado en MongoDB

        title:

          type: string

          description: Nombre del usuario

        description:

          type: string

          description: Apellido del usuario
        price: 

          type: number

          description: Precio del producto
        code: 

          type: string

          description: Codigo del producto
        stock:
          
          type: number
  
          description: Stock del producto
        status:
            
          type: boolean
            
          description: Estado del producto
        category:
          
          type: string
            
          description: Categoria del producto

      example:

        _id: "1f541bvs6t123bt"
        title: "Producto 1"
        description: "Descripcion del producto"
        price: 205
        code: "codigo1234"
        stock: 4
        status: true
        category: "categoria1"

  requestBodies:

    CreateProduct:
      type: object

      properties:

        title:

          type: string

          description: Nombre del usuario

        description:

          type: string

          description: Apellido del usuario
        price: 

          type: number

          description: Precio del producto
        code: 

          type: string

          description: Codigo del producto
        stock:
          
          type: number
  
          description: Stock del producto

        category:
          
          type: string
            
          description: Categoria del producto

      example:

        title: "Producto 1"
        description: "Descripcion del producto"
        price: 205
        code: "codigo1234"
        stock: 4
        category: "categoria1"

    UpdateProduct:

      type: object

      properties:

        title:

          type: string

          description: Nombre del producto

        description:

          type: string

          description: Descripcion del producto
        price: 

          type: number

          description: Precio del producto
        code: 

          type: string

          description: Codigo del producto
        stock:
          
          type: number
  
          description: Stock del producto
        status:
            
          type: boolean
            
          description: Estado del producto
        category:
          
          type: string
            
          description: Categoria del producto

      example:

        title: "Producto 1"
        description: "Descripcion del producto"
        price: 205
        code: "codigo1234"
        stock: 4
        status: true
        category: "categoria1"